"""empty message

Revision ID: 1d022bb20a69
Revises: d3295cb854c4
Create Date: 2021-07-30 19:05:42.288026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d022bb20a69'
down_revision = 'd3295cb854c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'delete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('delete', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
