"""empty message

Revision ID: 33425de4e923
Revises: 2e74d56a809a
Create Date: 2021-07-31 12:22:19.308834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33425de4e923'
down_revision = '2e74d56a809a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('update todolists set completed=False where completed is null;')
    op.alter_column('todolists','completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todolists', 'completed')
    # ### end Alembic commands ###
