"""empty message

Revision ID: 3d825607f22e
Revises: 33425de4e923
Create Date: 2021-07-31 22:55:54.822910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d825607f22e'
down_revision = '33425de4e923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todolists', 'completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.execute('update todolists set completed=False where completed is null;')
    op.alter_column('todolists','completed', nullable=False)
    # ### end Alembic commands ###
