"""empty message

Revision ID: d3295cb854c4
Revises: 0c70adcd42f5
Create Date: 2021-07-30 17:39:15.818381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3295cb854c4'
down_revision = '0c70adcd42f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.add_column('todos', sa.Column('delete', sa.Boolean(),nullable=True))
    op.execute('update todos set delete=False where delete is null;')
    op.alter_column('todos','delete', nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'delete')
    # ### end Alembic commands ###
